Documentation:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/LineLength:
  Max: 90
Metrics/MethodLength:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: consistent_comma
